# Generated by Django 3.0.3 on 2020-02-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBookStore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnixFile',
        ),
    ]
