# Generated by Django 3.0.3 on 2020-02-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.CharField(max_length=20)),
                ('givenName', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=20)),
                ('isbn13', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('seriesName', models.CharField(blank=True, max_length=100)),
                ('volumeNo', models.CharField(blank=True, max_length=3)),
                ('description', models.TextField(blank=True)),
                ('bookFormat', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('releaseDate', models.DateTimeField()),
                ('authors', models.ManyToManyField(blank=True, to='TestBookStore.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, to='TestBookStore.Book'),
        ),
    ]
