# Generated by Django 2.2.6 on 2020-02-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestBookStore', '0002_auto_20200207_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorId',
        ),
    ]
