# Generated by Django 3.0.3 on 2020-02-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBookStore', '0002_auto_20200207_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorId',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.CharField(max_length=100),
        ),
    ]
