# Generated by Django 3.0.3 on 2020-02-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestBookStore', '0004_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authorId',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='bookFormat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='releaseDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
